### ISSUE TITLE
○☓を入力し、盤面に反映させる。

### ISSUE THREAD

**Issue by t-kazu** [t-kazu/study_git#1]
your_trun関数に追記します。

**Comment by Ebikatsu** [comment]
○×を入力して盤面を変更した

before | after
---- | ----
![study-result1](https://cloud.githubusercontent.com/assets/23114771/26751004/93f8c170-486a-11e7-8bc5-50c89c2326e5.png) | ![study-result2](https://cloud.githubusercontent.com/assets/23114771/26751008/99b25284-486a-11e7-819e-1e9932cec495.png)

**Comment by t-kazu** [comment]
マージします

**Comment by nagasakotsuyoshi** [comment]
good luck
